image: roxsross12/node-chrome

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - deploy

frontend-test:
  stage: test
  script:
    - npm run test
  allow_failure: true 

pages:
  stage: deploy
  script:
    - npm install -g @angular/cli@10.1.3
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages      