name: workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  APP_ID: d1my6efm0i2l67
  REPONAME: demo-s3-a1
  BRANCH_NAME: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      # test the apps     
    - name: build
      run: |
          npm run build  
          
    - name: Create ZIP deployment package
      run: cd public;zip ../dist.zip * -r  
      
    - uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: dist.zip   
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:  
        name: node-app
   
    - name: Upload S3
      run:  aws s3 cp dist.zip s3://${{ env.REPONAME }}
      
    - name: Deploy
      run:  ./.github/scripts/amplify-deploy.sh 
      shell: bash
